#!/bin/bash
#Make sure only root can run our script
	if [[ $EUID -ne 0 ]]; then
	  echo "This script must be run as root" 1>&2
	  exit 1
	fi

apt-get install -fy git
apt-get -fy update

git config --global user.name "CCorrado"
git config --global user.email "ccorrads@gmail.com"
git clone https://github.com/ #repo name
#cd into repo dir
git status
git checkout #name of branch in repo (master, etc)
git status


